name: Publication request
description: Request to publish an IG
title: "Publish: <calculated>"
labels: ["publication-request"]

body:
  - type: markdown
    attributes:
      value: |
        **Package ID, Version, Canonical, and Site path will be calculated automatically from the repo (e.g., `sushi-config.yaml`) after you submit this issue.**
        The approver must review the computed values before approval.

  - type: textarea
    id: notes
    attributes:
      label: Notes / change summary
      placeholder: Anything reviewers should know…
